# Generated by Django 4.2.2 on 2023-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
